alias toWorkspace='cd /home/javielinux/Workspace'
alias to9Cards='cd /home/javielinux/Workspace/nine-cards-v2'
alias to9CardsBackend='cd /home/javielinux/Workspace/nine-cards-backend'
alias toDevSpark='cd /home/javielinux/Dev/spark-1.6.1-bin-hadoop2.6' 
alias toSparkProjects='/home/javielinux/Workspace/spark' 
